import type { Metadata } from "next";
import "./globals.css";
import Header from '../components/Common/Header'
import Footer from '../components/Common/Footer'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-sm">
        <div className="top leading-8 border-b">top</div>
        <div className="container max-w-5xl mx-auto">
          <Header></Header>
          {children}
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
